--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: william-eks
  region: eu-central-1

vpc:
  nat:
    gateway: Disable

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 2
