--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: william-eks
  region: eu-central-1

nodeGroups:
  - name: ng1-public
    instanceType: t3.micro
    desiredCapacity: 2
  
managedNodeGroups:
  - name: ng2-managed
    instanceType: t3.micro
    minSize: 1
    maxSize: 3
    desiredCapacity: 2  