--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: william-eks
  region: eu-central-1

nodeGroups:
  - name: ng-1
    instanceType: t3.micro
    desiredCapacity: 2
